version: "3.1"

services:

  core:
    build: .
    ports:
    - 8080:8080
    depends_on:
    - mongodb
    container_name: picpay-core
    links:
    - mongodb
    environment:
    - MONGO_HOST=picpay-mongodb

  mongodb:
    image: mongo:latest
    ports:
    - 27017:27017
    container_name: picpay-mongodb
#    volumes:
#    - ./data/mongo/db:/data/db
